### ISSUE TITLE
omgui:create-element throws error

### ISSUE THREAD

**Issue by hajovonta** [hemml/OMGlib#1]
hi,
attempted to try the example from the README page:

`(omgui:create-element "div" :|innerHTML| "Some text" :|style.fontWeight| "lighter")`

and got this error in the REPL:

`illegal sharp macro character: #\<

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(#<JS-OB...">
   [Condition of type SB-INT:SIMPLE-READER-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1001540533}>)

Backtrace:
  0: (SB-IMPL::SHARP-ILLEGAL #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> #\< #<unused argument>)
  1: (SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> #\#)
  2: (SB-IMPL::READ-LIST #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> #<unused argument>)
  3: (SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> #\()
  4: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> T (NIL) T)
  5: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> T (NIL) NIL)
  6: (READ #<SB-IMPL::STRING-INPUT-STREAM {7F6670BC5C63}> T NIL NIL)
  7: (SB-IMPL::%READ-FROM-STRING "(#<JS-OBJECT [object HTMLDivElement]>)" T NIL 0 NIL NIL)
  8: ((FLET OMG::EXEC :IN OMG:REMOTE-EXEC))
  9: (OMG:REMOTE-EXEC (OMGUI:CREATE-ELEMENT "div" :|innerHTML| "Some text" :|style.fontWeight| "lighter") NIL)
 10: (SB-INT:SIMPLE-EVAL-IN-LEXENV (OMGUI:CREATE-ELEMENT "div" :|innerHTML| "Some text" :|style.fontWeight| "lighter") #<NULL-LEXENV>)
 11: (EVAL (OMGUI:CREATE-ELEMENT "div" :|innerHTML| "Some text" :|style.fontWeight| "lighter"))
`

I'm using SBCL 2.1.6.31-7127ea27f

**Comment by hemml** [comment]
Hi!
This is because browser-side function trying to return DOM-object to the backend, which cannot be serialized. The return value of the `(create-element)` must be used on browser-side only.

**Comment by hajovonta** [comment]
hi @hemml, thanks for the answer! I'm not sure what does it mean, do I have to wrap it in a defun-f and discard the return value?

**Comment by hemml** [comment]
yes, look at `jslog` function in `omgui.lisp` (line 86), for example.
Anyway, this is a good practice to shift all the code working with UI to browser-side and transfer only simple data between backend and frontend.

**Comment by hajovonta** [comment]
Thanks, I understand now :)
