### ISSUE TITLE
The code assumes that (setf (apply #'gethash .. works, but it is not required in common-lisp

### ISSUE THREAD

**Issue by Yehouda** [hemml/OMGlib#4]
in omg.lisp, (setf gethash-lock)
https://github.com/hemml/OMGlib/blob/5926b201b09d4d03ef7dd6fb27e55af1e7b72ecd/omg.lisp#L53

uses    `(setf (apply #'gethash args) val)))`, but the common-lisp standard does not gurantee that this is a valid form. The standard only guarantees that **aref**, **bit** and **sbit** can be used this way.  For other standardized function it is left to the implementation.

 http://www.lispworks.com/documentation/HyperSpec/Body/05_abe.htm

In LispWorks it doesn't work
Since the arguments to gethash are known, there is no reason not to put them explicitly, Something like: 

```

(defun (setf gethash-lock) (val key table &optional default)
  (declare (ignore default)) ; (setf (getahsh ..)) also ignores the default
  (if *giant-hash-lock*
      (bt:with-lock-held (*giant-hash-lock*)
        (setf (gethash key table) val))
      (setf (gethash key table) val)))
```

**Comment by hemml** [comment]
Thank you for pointing to the issue! 
I have fixed it in the commit 5995b1514d0118a17510b818797125caa5b4d78b
I don't have LispWorks, so it will be nice if you check how OMGlib work in this environment, fell free to report any possible problems!

**Comment by Yehouda** [comment]
I am not actually using code directly from github, I am testing the libraries in quicklisp, so I will really test you change only after it isupdated in wuicklisp and we update our version from them.

With the (setf gethash-lock) that I had, it now compiles and loads on LispWroks (the reader was working already). 

In the fix ther eis a ditional line 572 `(print macro-res)`. Is that intentional?

**Comment by hemml** [comment]
The `(print macro-res)` was just a debug print, which I forgot to remove before (previous) commit, sorry)
